# Used for docker-compose local files that include the node performer
# A host mount is used instead of a file snapshot
FROM node:22-alpine

VOLUME ["/app"]
WORKDIR /app

EXPOSE 8080

CMD npm install && npm run dev:hot
